---
title: Genomic Selection
author: Omer Perach
date: '2020-06-17'
slug: genomic-selection
categories:
  - Big Data
  - Plant Science
tags:
  - Big Data
  - Plant Breeding
description: ''
topics: []
---

Hi there, I am excited!!!

What a beutiful subject to start with.

Supervised learning is the giant wave, storm, eathquake in almost every digital industry.

But what about non-tech industry? What about the agriculture and the breeding industries?

It starting to get warm, at least in the farming industry. A lot of companies aiming to retrieve data from the field such as aerial photography, soil water potential, satelite that can tract field temperature and soil radation. 

All for one point - achieve better yield with less resources. 

Yes, the farmer will be able to increase yield and lower operating expnse thus to increae revenue.

All of these endeavors have grat challenges and times will tell if the money to buy the technology will indeed help the famers. 

Some of the Israeli most interesting companies are: Prospera, Taranis, SeeTree, CropX.

To be honest, we need to disrupt the gene to phenotype challenge in order to feed 10 the world in the future

How we will do it? you will need to continue reading...



